### ISSUE TITLE
"<android install-location="preferExternal" />" tag seems to have been already abolished.

### ISSUE THREAD

**Issue by utibenkei** [openfl/openfl.org#20]
at page http://www.openfl.org/documentation/projects/project-files/xml-format/

**Comment by kevinresol** [comment]
use this 
```xml
<set name="ANDROID_INSTALL_LOCATION" value="auto" if="android" />
```

referece:
https://github.com/openfl/lime/blob/ef86c425b1f6d01f7b016fc5e1f4df5260a35766/lime/project/ProjectXMLParser.hx#L774

**Comment by jgranick** [comment]
Does this work?

```xml
<config:android install-location="auto" />
```

**Comment by kevinresol** [comment]
@jgranick yes both your code and mine worked

**Comment by jgranick** [comment]
Okay, good :smile: 

The `<config:android />` or `<config:ios />` tags are to replace the `<android />` and `<ios />` tags (which I never liked), though for backward compatibility, this should be fixed.

It's not perfect yet, but `<config />` can hold custom unstructured data, which could help us config a lot more things in the future :smile:

**Comment by jgranick** [comment]
I've updated the page:

http://www.openfl.org/learn/resources/command-line-tools/project-files/xml-format/

We need to set up redirects, though, from the older "/documentation" links
