### ISSUE TITLE
Update readme

### ISSUE THREAD

**Issue by frenetic** [openfl/openfl.org#37]
The currently readme is outdated.
Right now, there is no Wiki under OpenFL repository. The current script inside **_tools** directory compiles data from the [documentation repository](https://github.com/openfl/openfl-documentation).

A Big plus would be symlinking the documentation repository inside this repository, and updating the [import documentation script](https://github.com/openfl/openfl.org/blob/master/_tools/import-documentation/ImportDocumentation.hx) to make use of this.

**Comment by jgranick** [comment]
Thanks! I just removed that section of the wiki, the documentation is built from the https://github.com/openfl/openfl repository now :smile:
