### ISSUE TITLE
Out of date documentation still accessible

### ISSUE THREAD

**Issue by ibilon** [openfl/openfl.org#45]
See: http://community.openfl.org/t/how-rebuild-lime/1770

It references this page: http://www.openfl.org/documentation/advanced-setup/development-builds/

but I couldn't find a link from the website to any page in the `documentation/` subfolder,
shouldn't they be removed?

**Comment by flashultra** [comment]
I think the  page http://www.openfl.org/documentation/ should be alive and accessible from the site, because only there have information how to install OpenFL . It is mistake to miss this link  . Maybe it should have new section in the header ?

**Comment by ibilon** [comment]
Still an issue,
https://github.com/openfl/openfl/issues/980

@jgranick how do you deploy the website?
Could be worth doing a clean upload.
