### ISSUE TITLE
Not visible blog posts

### ISSUE THREAD

**Issue by flashultra** [openfl/openfl.org#60]
Now if choose News section link redirect me to https://www.twitter.com/open_fl/ , before was 
http://www.openfl.org/blog/ . Also link OpenFL 4 is Live ( http://www.openfl.org/blog/2016/07/11/openfl-4-is-live/ ) return error

**Comment by jgranick** [comment]
We have changed to a "News" link to Twitter, for now, as that has more current detail than the blog might. In the future, we may redesign the Blog page to integrate current news and longer posts better, but for now, Twitter will link to the blog when there is something new there.
