### ISSUE TITLE
Bump default haxe to 3.4.0 (and neko to 2.1.0)

### ISSUE THREAD

**Issue by IBwWG** [openfl/openfl.org#76]
By which I mean, change [the install script provided (at least for Linux)](http://www.openfl.org/builds/haxe/haxe-3.2.1-linux-installer.tar.gz) and make new installers for Win and Mac.

TL;DR: the Linux install script also needed some touchups to continue working with haxe 3.4.0 (which needs neko 2.1.0)--not just a version bump.  Issues affected both 32- and 64-bit linux.  A working script is at https://gist.github.com/IBwWG/4e60d12e8acd1f9031fd4a14780ef2f4

______________________________________

Careful of an issue on 32-bit Linux though.  On 64-bit Linux I just unzipped 3.4.0 overtop /usr/lib/haxe, which was already there having used the openfl-provided 3.2.1 install script.  On 32-bit, doing this made haxelib no longer start, complaining about libneko.so.2.  Making a link with `ln -s libneko.so libneko.so.2` makes that error go away but instead you get `haxelib: symbol lookup error: haxelib: undefined symbol: elf_find_embedded_bytecode`.  At this point I thought I should try just bumping the version number in openfl's install script and running that, but the results are no different.  Whether they would have been from the beginning, I'm not sure.

**Comment by IBwWG** [comment]
I think it would have given the same result.  I just got rid of the libneko.so.2 symlink and tried the install script with the bumped version number, and again we're back to `haxelib: error while loading shared libraries: libneko.so.2: cannot open shared object file: No such file or directory` whenever you try to simply run `haxelib`.

The neko version didn't change from 2.0.0.  I guess something in haxelib changed, then.

Putting the haxe version back to 3.2.1 and rerunning the install script results in a working haxe installation again.

**Comment by IBwWG** [comment]
So maybe this is not an issue with openfl's install script, but an issue with haxelib 3.3.0 that comes with haxe 3.4.0, only on linux32?

**Comment by IBwWG** [comment]
Just noticed that https://github.com/HaxeFoundation/haxe#version-compatibility says haxe 3.4.0 is only compatible with neko 2.1.0.  (Funny that it works nonetheless on linux64.)

Bumping the neko version as well in the install script did not yield any different results.

Aha, but adding the symlink back in *did* fix everything, instead of giving that elf error.  So that should be included on 32-bit platforms.

**Comment by IBwWG** [comment]
It seems both symlinks are not needed: `haxelib` starts fine if there's only the `.2` version there.

**Comment by IBwWG** [comment]
Tried bumping the neko version under linux64 and it gives a different problem.  BTW, where does the install script actually live?  The link is at https://github.com/openfl/openfl.org/blob/master/learn/docs/getting-started.md but I don't see the build directory in the tree, and searching the code didn't seem to yield anything (for NEKO_VERSION, e.g.)

**Comment by IBwWG** [comment]
Being that I don't know where the installer should actually go, here's [a fixed gist that should work for 32- and 64-bit linux](https://gist.github.com/IBwWG/16debd85c78c8943b83758292b6b2b43).

**Comment by jgranick** [comment]
Thanks for your work on this! We're going to try doing the PPA version for now, and hopefully that doesn't end up being a problem, but we're keeping the install scripts in a back pocket in case :smile:

**Comment by sonygod** [comment]
is this sh work on Centos?

**Comment by jgranick** [comment]
I believe so
