### ISSUE TITLE
blog's RSS feed is invalid

### ISSUE THREAD

**Issue by codingthat** [openfl/openfl.org#81]
If I go to http://www.openfl.org/blog/rss.xml in Chromium for Linux, I get this message:

> This page contains the following errors:
> 
> error on line 13 at column 62: Entity 'nbsp' not defined
> Below is a rendering of the page up to the first error.
> 
> OpenFL http://www.openfl.org RSS feed for OpenFL Wed, 15 Mar 2017 00:00:00 -0700

**Comment by codingthat** [comment]
Confirmed this is still happening.

Sorry to have framed it academically rather than practically.  The end result for me is that via my RSS aggregator, which gives a similar error trying to read the feed, gives me no OpenFL news.  I'm not sure how many others are affected by this, but they seem to use a fairly common library (LibXML) so...

**Comment by jgranick** [comment]
I have just changed the library used to generate our feeds. Could you give it a try again, and see if it works better for you? Thank you :smile:

**Comment by codingthat** [comment]
Yep, it works great!  Thanks!  :smile:
